name: PR Trigger

on:
  pull_request_target:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read
  actions: write

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CI workflow on PR branch
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'ci.yml',
              ref: context.payload.pull_request.head.ref,
              inputs: {
                pr_number: context.payload.pull_request.number.toString(),
                pr_sha: context.payload.pull_request.head.sha,
              },
            })
